### ISSUE TITLE
InteriorLeftNav component is not exported

### ISSUE THREAD

**Issue by moores2** [carbon-design-system/carbon-addons-bluemix#9]
## Detailed description

The InteriorLeftNav component is not exported via index.js and thus cannot be used by client code. Carbon components gives the warning "Accessing the `interior-left-nav` component from the `carbon-components`package is deprecated. Use the `carbon-addons-bluemix` package instead.", however this appears not to be possible because it is not exported. Other components are also not exported, which may also be an issue.

> Is this issue related to a specific component? InteriorLeftNav

> What version of the Carbon Design System are you using? 8.0.1

## Steps to reproduce the issue

1. Try to use InteriorLeftNav from an npm installed carbon-addons-bluemix package.

**Comment by joshblack** [comment]
Should be solved by this PR, right @marijohannessen ? https://github.com/carbon-design-system/carbon-addons-cloud/pull/9

**Comment by murtdagi** [comment]
I am having the same issue, when i try to use interior-left-nav from carbon-components it says its deprecated, but when i try to use interior-left-nav from carbon-addons-bluemix it cannot resolve some of the scss files imported in the interior-left-nav.scss because the imports are not preceded with a ~ sign.
I tried preceding all the imports in interior-left-nav.scss with a ~ sign in carbon-addons-bluemix and it works.........
Can i request you to fix this please?

**Comment by joshblack** [comment]
Hi @murtdagi! Did you make sure to include `node_modules` in your `node-sass` `includePaths` config?

**Comment by murtdagi** [comment]
Hi.......yes that solved the problem for me......Thanks

**Comment by tw15egan** [comment]
🎉
